version: '3.8'

networks:
  rag_network:
    driver: bridge  # You can specify the driver if needed, 'bridge' is the default

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"  # Expose port 11434 for external access
    networks:
      - rag_network  # Connect to the custom network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ragserver
    depends_on:
      - ollama
      - qdrant
    ports:
      - "8080:8080"
    networks:
      - rag_network  # Connect to the custom network
    environment:
      - QDRANT_PORT=6333
      - QDRANT_CONTAINER_NAME=qdrant

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - rag_network